import { buildLevel, type LevelBlueprint } from '../game/LevelManager'

const level7: LevelBlueprint = {
  id: 7,
  name: 'The Long Hall',
  subtitle: 'It is faster now. The alcoves will not save you. They will help you.',
  briefing: [
    'It is faster now.',
    'The alcoves hold light. Light holds it still.',
    'Reach a checkpoint. Catch your breath. Move again.',
    'The exit is at the very bottom. It will be waiting there too.',
  ],
  map: [
    '####################',
    '#..................#',
    '#.P................#',
    '#............#.....#',
    '#............#..T..#',
    '#............#.....#',
    '#............#.....#',
    '#..................#',
    '#...............C..#',
    '#............#.....#',
    '###########..#.....#',
    '#............#.....#',
    '#............#..T..#',
    '#............#.....#',
    '#............#.....#',
    '#..................#',
    '#...............C..#',
    '#............#.....#',
    '#.........##########',
    '#............#.....#',
    '#............#..T..#',
    '#............#.....#',
    '#............#.....#',
    '#..................#',
    '#...............C..#',
    '#............#.....#',
    '##############.....#',
    '#..................#',
    '#.E..............W.#',
    '#..................#',
  ],
  creature: { speed: 118, chaseMul: 1.4, reactDelay: 0.3 },
  ambient: { darkness: 0.94, tint: 'rgba(10,10,18,0.3)', flickerIntensity: 1.3, whisperChance: 0.35 },
  player: { speed: 168 },
  prowl: [
    { x: 4 * 48 + 24, y: 3 * 48 + 24 },
    { x: 17 * 48 + 24, y: 7 * 48 + 24 },
    { x: 4 * 48 + 24, y: 15 * 48 + 24 },
    { x: 17 * 48 + 24, y: 22 * 48 + 24 },
    { x: 4 * 48 + 24, y: 27 * 48 + 24 },
  ],
  overrides: {
    spotlights: {
      T_16_4: { faceDir: 'west', active: true },
      T_16_12: { faceDir: 'west', active: true },
      T_16_20: { faceDir: 'west', active: true },
    },
  },
}

export default buildLevel(level7)
